### ISSUE TITLE
Post request doesn't work

### ISSUE THREAD

**Issue by piratack007** [tourniquet-io/simple-rest-client#1]
Hi

I would like to post a request like this:

`
package simpleRestClient;

import javax.json.Json;
import javax.json.JsonWriter;
import javax.json.JsonObject;

public class Main {
	
	 public static JsonObject jsonObject;

	public static void main(String[] args) {
		
		
		jsonObject = Json.createObjectBuilder()
			     .add("name", "eclipse")
			     .add("price", "25")
			     .add("description","description")
			     .add("category_id","4")
			     .add( "created" , "2018-06-01 00:35:07")
			     .build();
		
		 SimpleRestClient.requestTo("http://localhost/test/apiRest/product/create.php")
                .acceptJson() //accept header
                .sendJson() //conent type header
                .post(os -> {
                   try (JsonWriter w = Json.createWriter(os)) {
                	  
                      w.writeObject(jsonObject);
                   }
                })
                .asString();
	}

}
`

This is what i have got as error

Exception in thread "main" javax.json.JsonException: Provider org.glassfish.json.JsonProviderImpl not found
	at javax.json.spi.JsonProvider.provider(JsonProvider.java:97)
	at javax.json.Json.createObjectBuilder(Json.java:266)
	at simpleRestClient.Main.main(Main.java:19)
Caused by: java.lang.ClassNotFoundException: org.glassfish.json.JsonProviderImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at javax.json.spi.JsonProvider.provider(JsonProvider.java:94)
	... 2 more

where is the problem please?

regards

**Comment by piratack007** [comment]
after some research i have to add a dependency

<dependency>
    <groupId>org.glassfish</groupId>
    <artifactId>javax.json</artifactId>
    <version>1.1</version>
</dependency>
